spring:
  datasource:
    url: jdbc:mysql://localhost/SISTEMA_INVESTIMENTO?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: tamburu
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/user
  