version: '3'

services:
  db:
    container_name: db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: sistema_investimento
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql:/var/lib/mysql
  backend:
    container_name: backend
    build: .
    depends_on:
      - db
    ports:
    - "8080:8080"
    restart: always

volumes:
  mysql:
