spring:
  datasource:
    url: jdbc:mysql://localhost/Auth?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: tamburu
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
